<?php
echo json_encode([
	[
		'optype' => 0,
		// 'sname' => 'sname',
		// 'scompany' => 'scompany',
  //       'saddress' => 'saddress',
  //       'slat' => 'slat',
  //       'slng' => 'slng',
  //       'sphone' => 'sphone',
  //       'szipcode' => 'szipcode',
  //       'rname' => 'rname',
  //       'rcompany' => 'rcompany',
  //       'raddress' => 'raddress',
  //       'rlat' => 'rlat',
  //       'rlng' => 'rlng',
  //       'rphone' => 'rphone',
  //       'rzipcode' => 'rzipcode',
  //       'cargoweight' => 'cargoweight',
  //       'cargovolume' => 'cargovolume',
  //       'beginsenddate' => 'beginsenddate',
  //       'endsenddate' => 'endsenddate',
  //       'freight' => 'freight',
  //       'totalfee' => 'totalfee',
  //       'collectionfee' => 'collectionfee',
  //       'paytype' => 'paytype',
  //       'paystatus' => 'paystatus',
  //       'begintime' => 'begintime',
  //       'bindflag' => 'bindflag',
  
        'trunkcode' => 'trunkcode',
        'endpoint' => 'endpoint',
        'startpoint' => 'startpoint',
        'trunkname' => 'trunkname',
        'plantask' => 'plantask',
        'remark' => 'remark',
        'progress' => 'progress',
        'arrivetime' => 'arrivetime',
        'trunkstatus' => 'trunkstatus',
        'cargovolume' => 'cargovolume',
        'cargoweight' => 'cargoweight',
        'bindflag' => 'bindflag',
        'autorelease' => 'autorelease',

        'taskcode' => 'zzzaaaa',
        'ordercode' => 'ordercode2',
        'currstatus' => 1000,
        'statustext' => 'statustext',
        'postionlog_id' => 'postionlog_id',
        'currlat' => '0',
        'currlng' => '0',
        'postmanid' => 'asads',
        'postmanname' => '张三58',
        'truckid' => '',
        'carnum' => '导A00017',
        'remark' => 'remark',
        'picnum' => '0',
        'donetype' => 'donetype',

        'field_1' => '自定义'
	]
]);
